db.createCollection("test");
db.test.insertMany([
  {
    artist: {
      id: "74gcBzlQza1bSfob90yRhR",
      name: "City and Colour",
      topTracks: [
        "spotify:track:39dnj8G8DK6I1JmNOZKeZO",
        "spotify:track:5y2H3YMH4BcIVMYaqr7NPB",
        "spotify:track:6bpoSwD4xu2WWIVQH07LMa",
        "spotify:track:7G9yE2L2bXxqaQKVL2rKAr",
        "spotify:track:0SwUDplbBp66rM5sMC0eD7",
        "spotify:track:65HOlqJpNqaUbateZw2GrA",
        "spotify:track:29BYcl5IptV6B5jfJRNq4o",
        "spotify:track:58CHujf89H5cuuZqm4RaLn",
        "spotify:track:3cNyJCm0nf1DPr6hvSLu8Q",
        "spotify:track:5Cn9nBZh530Vei9dOeKUGs",
      ],
      uri: "spotify:artist:74gcBzlQza1bSfob90yRhR",
      albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02fcd095743d626051079163f3",
      link: "https://open.spotify.com/artist/74gcBzlQza1bSfob90yRhR",
    },
    date: "2025-02-18",
    venue: "Save On Foods Arena",
  },
  {
    artist: {
      id: "02seUFsFQP7TH4hLrTj77o",
      name: "Nathaniel Rateliff & The Night Sweats",
      topTracks: [
        "spotify:track:1VPUpUwtbpoRVXt0txVU0w",
        "spotify:track:7ADBL3WZ9Oyj7zgkg7ODT8",
        "spotify:track:1q5wF1wZQD41ura41yVqXb",
        "spotify:track:6YfEvtwpQwGAWZBWzNmoIw",
        "spotify:track:2YhAqgvjzU2Rw44rAqzGl6",
        "spotify:track:71DxoKxpHcW8iaYNczwGi3",
        "spotify:track:5yTpyXVKcB20zOGXU1ffgf",
        "spotify:track:4nXmBb2s8Mmkq2hGskHxiq",
        "spotify:track:5rHUY5EUCtdE7a9qUJblQC",
        "spotify:track:5q15dlrrKO1ubSZAciVQgl",
      ],
      uri: "spotify:artist:02seUFsFQP7TH4hLrTj77o",
      albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02e564c5e6be9e9cace137b989",
      link: "https://open.spotify.com/artist/74gcBzlQza1bSfob90yRhR",
    },
    date: "2025-03-02",
    venue: "Save On Foods Arena",
  }
]);

db.createCollection("victoria");
db.victoria.insertMany([
  {
    artist: "City and Colour",
    ticket_date: "2025-02-18 at Save On Foods Arena",
    venue: "Save On Foods Arena",
    date: "2025-02-18",
    band_id: "74gcBzlQza1bSfob90yRhR",
    sp_band_name: "City and Colour",
    link: "https://open.spotify.com/artist/74gcBzlQza1bSfob90yRhR",
    uri: "spotify:artist:74gcBzlQza1bSfob90yRhR",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02fcd095743d626051079163f3",
    topTrackURIs: [
      "spotify:track:39dnj8G8DK6I1JmNOZKeZO",
      "spotify:track:5y2H3YMH4BcIVMYaqr7NPB",
      "spotify:track:6bpoSwD4xu2WWIVQH07LMa",
      "spotify:track:7G9yE2L2bXxqaQKVL2rKAr",
      "spotify:track:0SwUDplbBp66rM5sMC0eD7",
      "spotify:track:65HOlqJpNqaUbateZw2GrA",
      "spotify:track:29BYcl5IptV6B5jfJRNq4o",
      "spotify:track:58CHujf89H5cuuZqm4RaLn",
      "spotify:track:3cNyJCm0nf1DPr6hvSLu8Q",
      "spotify:track:5Cn9nBZh530Vei9dOeKUGs",
    ],
  },
  {
    artist: "Nathaniel Rateliff & The Night Sweats",
    ticket_date: "2025-03-02 at Save On Foods Arena",
    venue: "Save On Foods Arena",
    date: "2025-03-02",
    band_id: "02seUFsFQP7TH4hLrTj77o",
    sp_band_name: "Nathaniel Rateliff & The Night Sweats",
    link: "https://open.spotify.com/artist/02seUFsFQP7TH4hLrTj77o",
    uri: "spotify:artist:02seUFsFQP7TH4hLrTj77o",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02e564c5e6be9e9cace137b989",
    topTrackURIs: [
      "spotify:track:1VPUpUwtbpoRVXt0txVU0w",
      "spotify:track:7ADBL3WZ9Oyj7zgkg7ODT8",
      "spotify:track:1q5wF1wZQD41ura41yVqXb",
      "spotify:track:6YfEvtwpQwGAWZBWzNmoIw",
      "spotify:track:2YhAqgvjzU2Rw44rAqzGl6",
      "spotify:track:71DxoKxpHcW8iaYNczwGi3",
      "spotify:track:5yTpyXVKcB20zOGXU1ffgf",
      "spotify:track:4nXmBb2s8Mmkq2hGskHxiq",
      "spotify:track:5rHUY5EUCtdE7a9qUJblQC",
      "spotify:track:5q15dlrrKO1ubSZAciVQgl",
    ],
  },
  {
    artist: "ATYYA",
    ticket_date: "2025-03-03 at Capital Ballroom",
    venue: "Capital Ballroom",
    date: "2025-03-03",
    popularity: { $numberInt: "40" },
    band_id: "36NAuk7D3nO0JFfgZf3XI7",
    sp_band_name: "ATYYA",
    link: "https://open.spotify.com/artist/36NAuk7D3nO0JFfgZf3XI7",
    uri: "spotify:artist:36NAuk7D3nO0JFfgZf3XI7",
    albumArtUrl: "https://i.scdn.co/image/b2c37bb21b1c87bc6a1321fdaf9496d1300a5fc2",
    topTrackURIs: [
      "spotify:track:3JM7koFXQKs2dE4tk3rccc",
      "spotify:track:3xQasdSXUXp0LhERjcORNQ",
      "spotify:track:7bz3aBvfS99RkIumQnM7Fo",
      "spotify:track:50hrbF953adalRazqEy6QO",
      "spotify:track:5hsEDtyXqZdZ53wgafNRYi",
      "spotify:track:5crdzbBZhjn8MMFhj4gDlq",
      "spotify:track:1sVeutIp3sh1eePjz7ONnH",
      "spotify:track:2M2tiV6brl9goTBevuYRa7",
      "spotify:track:7bhxpYCqZ2W3bf6mTYt5u0",
      "spotify:track:15Er0c4Xm78iNQFlwdjqpT",
    ],
  },
  {
    artist: "Defunk",
    ticket_date: "2025-03-04 at Distrikt",
    venue: "Distrikt",
    date: "2025-04-04",
    popularity: { $numberInt: "18" },
    band_id: "79OsU8JudFdMQxQTnyOJcF",
    sp_band_name: "Defunk",
    link: "https://open.spotify.com/artist/79OsU8JudFdMQxQTnyOJcF",
    uri: "spotify:artist:79OsU8JudFdMQxQTnyOJcF",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e026bcea188dd886071929062e4",
    topTrackURIs: [
      "spotify:track:4i1hJrK9ZJ9oc3btoKFv6H",
      "spotify:track:20bXCMaPupQ3ZQlURtRR9D",
      "spotify:track:3ipgpH1o7gtXhoXyrEgziA",
      "spotify:track:0qEWe3qaFhkwFCbsZIBwo9",
      "spotify:track:6e0MGFVOXLm8O4immWmQvt",
      "spotify:track:5aOX7PvuigO8bJVNP7wfgV",
      "spotify:track:08ebLgZ0Motu8QFjCt8WMS",
      "spotify:track:75aXvgHNwpOpD4H0G6mxE6",
      "spotify:track:4f1oGVXrISPUXOI0rLku20",
      "spotify:track:3JXJTjPZKwCJPOK3plWzR5",
    ],
  },
  {
    artist: "Ora Cogan",
    ticket_date: "2025-04-02 at Lay Away",
    venue: "Lay Away",
    date: "2025-04-02",
    popularity: { $numberInt: "20" },
    band_id: "0zZHy0tQvwi4L5HNvNq0QY",
    sp_band_name: "Ora Cogan",
    link: "https://open.spotify.com/artist/0zZHy0tQvwi4L5HNvNq0QY",
    uri: "spotify:artist:0zZHy0tQvwi4L5HNvNq0QY",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02d9187389bf9d411028117a68",
    topTrackURIs: [
      "spotify:track:5JXvUtS7GJunlM32p4HmhZ",
      "spotify:track:3toei8F88SwEBhgAI5AnvO",
      "spotify:track:7eaTwpkcfYZGz32CtS7MbJ",
      "spotify:track:7JlZQhetTFRlCT5RatEoLY",
      "spotify:track:5xoNh4oqywoIQOJGEHsxm5",
      "spotify:track:6oGgGKxq5UVueRcTureqGz",
      "spotify:track:4YKKbE9KbeSC1FjYm6H2X7",
      "spotify:track:1afzfur0DtwBSCDDI3bPVA",
      "spotify:track:2tLYCWeoD8xtDcHwk6HcyE",
      "spotify:track:65pumoKFYiXNDjE5vwNtED",
    ],
  },
]);

db.createCollection("phillipsBackyard");
db.phillipsBackyard.insertMany([
  {
    artist: "Lord Huron",
    ticket_date: "July 7 at TILT",
    venue: "TILT",
    date: "2023-07-07",
    day: "July 7",
    popularity: { $numberInt: "0" },
    band_id: "6ltzsmQQbmdoHHbLZ4ZN25",
    sp_band_name: "Lord Huron",
    link: "https://open.spotify.com/artist/6ltzsmQQbmdoHHbLZ4ZN25",
    uri: "spotify:artist:6ltzsmQQbmdoHHbLZ4ZN25",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e029d2efe43d5b7ebc7cb60ca81",
    topTrackURIs: [
      "spotify:track:0QZ5yyl6B6utIWkxeBDxQN",
      "spotify:track:5JVlz4JCy3cv8pZB12sKJL",
      "spotify:track:1KQsrNv2vEW7AXKTrFz0Ah",
      "spotify:track:1bqrRn1pJWowNLA5N9L6uW",
      "spotify:track:7xQg5QTx8eiQnsxEnfynPh",
      "spotify:track:6xVd8klTvL6ZRovgIhIs98",
      "spotify:track:4UGoW08gaqIEWNTam1UNen",
      "spotify:track:3oTGPCFE3UfBXQk0eLmTRT",
      "spotify:track:4c2k3NdkIwhi0eogpTnteI",
      "spotify:track:4FE9SgxcOoCNuGnaaU8TXz",
    ],
  },
]);

db.createCollection("rifflandia");
db.rifflandia.insertMany([
  {
    ticket_band: "Iggy Pop",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "100100" },
    band_id: "33EUXrFKGjpUSGacqEHhU4",
    sp_band_name: "Iggy Pop",
    link: "https://open.spotify.com/artist/33EUXrFKGjpUSGacqEHhU4",
    uri: "spotify:artist:33EUXrFKGjpUSGacqEHhU4",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02fe455cf2635dc2c6a6816a66",
    topTrackURIs: [
      "spotify:track:24FmdHoCr2jZGE6Z6dZbJT",
      "spotify:track:3IRvvlj2KpYoH76mLacnsp",
      "spotify:track:6ZAwEE4kTdtvyE66iRhFxR",
      "spotify:track:2nQmWhZWggVGkfZnzodGeO",
      "spotify:track:1ojRut8t5RYNmLpJkEdJ3V",
      "spotify:track:27BATZe36zHNAKfr7by2ob",
      "spotify:track:6OGIBcJV5qV1FF5uiofnX0",
      "spotify:track:17G8acTUbdbbd6DCmAi5Nb",
      "spotify:track:7hwFJ4XTiVOrk12z7SvQUT",
      "spotify:track:2oQHrYlOkgh4dZ5v7nAdVG",
    ],
  },
  {
    ticket_band: "Marc Rebillet",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: {
      $numberInt: "100900",
    },
    band_id: "72udTJKu1pGovvS9aCYGMI",
    sp_band_name: "Marc Rebillet",
    link: "https://open.spotify.com/artist/72udTJKu1pGovvS9aCYGMI",
    uri: "spotify:artist:72udTJKu1pGovvS9aCYGMI",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02a45a839cb6f2ee4f0b10505f",
    topTrackURIs: [
      "spotify:track:6voMS2OL56W3oVdAjikb4X",
      "spotify:track:7iXA7a53fVKxPJFJvebJ8P",
      "spotify:track:5WKs5nHNseedSb4tJMPU8J",
      "spotify:track:5fZRnSsCC4AHOZFZ6lNWqw",
      "spotify:track:0TtqzjTAoUbpxyfl2rvOXe",
      "spotify:track:7D9DLTNVLE0JCCMKj3ii53",
      "spotify:track:6wnHoCmuj9Y1y9l6mntke6",
      "spotify:track:6QcsVmeFQX6zt2TeVu9uQW",
      "spotify:track:1GQ0EBUPYDdgTugzuflubV",
      "spotify:track:0eXtOOP1KX09M5BpeUpdaq",
    ],
  },
  {
    ticket_band: "Suicidal Tendencies",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "101300" },
    band_id: "3WPKDlucMsXH6FC1XaclZC",
    sp_band_name: "Suicidal Tendencies",
    link: "https://open.spotify.com/artist/3WPKDlucMsXH6FC1XaclZC",
    uri: "spotify:artist:3WPKDlucMsXH6FC1XaclZC",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02ff66248fdc73fb872acf7087",
    topTrackURIs: [
      "spotify:track:7G83ZwD2msTtFaBQExc8QB",
      "spotify:track:3I9K8tSZRsAw7bRYfbhJEA",
      "spotify:track:203xxdlledLFnkqrUleD72",
      "spotify:track:2zeAo1ddhjm1TioD77dDSV",
      "spotify:track:03HL3jTzizrDNtPcmdPELp",
      "spotify:track:2ytzNU7aRj6ro9OCiaMExq",
      "spotify:track:4dJYU1M9aXvfH3rnqRQIZq",
      "spotify:track:2YWneK5JPbsfYuFMFgEon7",
      "spotify:track:4nbkJukvqC7ae4kIICjEPi",
      "spotify:track:0JoHFDx1gp0JjBxEIPutNK",
    ],
  },
  {
    ticket_band: "Two Feet",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "101800" },
    band_id: "5sWHDYs0csV6RS48xBl0tH",
    sp_band_name: "Two Feet",
    link: "https://open.spotify.com/artist/5sWHDYs0csV6RS48xBl0tH",
    uri: "spotify:artist:5sWHDYs0csV6RS48xBl0tH",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02fe3a12c23f04549cef0fbe84",
    topTrackURIs: [
      "spotify:track:3aauaXWRgwCMoykMbI0Jq1",
      "spotify:track:4NZrZgrRoR4GwR7flWOXRI",
      "spotify:track:6MiVIH3fQlmz44jGx2DXn4",
      "spotify:track:7tZdkPtebOG29TzPPHlsem",
      "spotify:track:6gGBL1uMBcNUOzSYfKreID",
      "spotify:track:7cS8eqcw4EQraaGYcUAANo",
      "spotify:track:1pV3J1Zk5mh20ncHiGlPhe",
      "spotify:track:3lML37ujKr8GdxQqCYkCoz",
      "spotify:track:4Zgo9uf4jURl7tjCBmUjy2",
      "spotify:track:7aW115ZGsZcA0Y2HQxiUIU",
    ],
  },
  {
    ticket_band: "U.S. Girls",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "102200" },
    band_id: "3AHFDfqhSqPBecjQDIOIJA",
    sp_band_name: "U.S. Girls",
    link: "https://open.spotify.com/artist/3AHFDfqhSqPBecjQDIOIJA",
    uri: "spotify:artist:3AHFDfqhSqPBecjQDIOIJA",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e021fe365b735112bcc5ebb4917",
    topTrackURIs: [
      "spotify:track:1bmI4c3p9OxjLrSrorcVUr",
      "spotify:track:6DGL39cV0SMFRJMEWN3qiJ",
      "spotify:track:6fx7gWBYL9eq2BfbiaiV5d",
      "spotify:track:4GZ0mDOTfdYEFqhddeguic",
      "spotify:track:5DeWIpInDjr5tlVuqQZyVO",
      "spotify:track:5HV0EyPWnLuEtoUkDBVsiT",
      "spotify:track:4G4mwvQFMNZ3VEJVDqw2AF",
      "spotify:track:5qSeU9NojSgSi5cAy5Fyey",
      "spotify:track:1Rtcq2RErgV3NuQvKdCNf6",
      "spotify:track:7vZpXEMtxxXrYvHoANeYRH",
    ],
  },
  {
    ticket_band: "Sports Team",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "102500" },
    band_id: "04JIxSs2P0iteVWtaskfeh",
    sp_band_name: "Sports Team",
    link: "https://open.spotify.com/artist/04JIxSs2P0iteVWtaskfeh",
    uri: "spotify:artist:04JIxSs2P0iteVWtaskfeh",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02ed27f8a3acd9cdccc3c20950",
    topTrackURIs: [
      "spotify:track:7zWPaL2lqEuGnsNCK6WE40",
      "spotify:track:4jMCKf7hqXSRv7DD9ZcMVZ",
      "spotify:track:6VqMZB5aLHiuAzNUIZzgFL",
      "spotify:track:4o7s44EemK0x9LXdER4CCL",
      "spotify:track:3vxD9sbFvp0auozLSP64J7",
      "spotify:track:231eK9ljMuQeKkjsInGHSo",
      "spotify:track:364wfG3SxoEbcvOGEmn3u5",
      "spotify:track:53L6fPrYdGkLaYou4Tartf",
      "spotify:track:4KxsWrAuXBQcHw3qNWkZ5A",
      "spotify:track:2U05tgFQF9dT92UstG9XTw",
    ],
  },
  {
    ticket_band: "The Poor Choices",
    ticket_date: "Sept 15 @ The Park",
    weekend: "The Park",
    date: "Sept 15",
    day: "Sept 15",
    orderNum: { $numberInt: "107000" },
    band_id: "4zfscUlBboSxhftEQub2yN",
    sp_band_name: "The Poor Choices",
    link: "https://open.spotify.com/artist/4zfscUlBboSxhftEQub2yN",
    uri: "spotify:artist:4zfscUlBboSxhftEQub2yN",
    albumArtUrl: "https://i.scdn.co/image/ab67616d000048514a93d609cf16b41fbdc3a0f2",
    topTrackURIs: [
      "spotify:track:6XxXKl2y8Jv7Amo6T0hOUc",
      "spotify:track:0azKBnzKzDPd23RQLxTkKi",
      "spotify:track:7vVi9hBzbmDfaxM87SxqvW",
      "spotify:track:0VUPxoR1X66EVtNqZ7fPI0",
      "spotify:track:1O4vQKk1UVrdhFjDo23KLG",
      "spotify:track:1SLbQMHSt9GW9fs4Zm6qfG",
      "spotify:track:4vnBu0aAe4iA3Yne8BzAh5",
      "spotify:track:5RHETPnBX7VYJQKa4rqgVn",
      "spotify:track:3U9FEzOguvsilI2ZCxcBoi",
      "spotify:track:38xgpYDOlvchWirY8WAlk4",
    ],
  },
  {
    ticket_band: "Diplo",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "100200" },
    band_id: "5fMUXHkw8R8eOP2RNVYEZX",
    sp_band_name: "Diplo",
    link: "https://open.spotify.com/artist/5fMUXHkw8R8eOP2RNVYEZX",
    uri: "spotify:artist:5fMUXHkw8R8eOP2RNVYEZX",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02d79c10cdf4a58309a37d195a",
    topTrackURIs: [
      "spotify:track:3FU6urUVsgXa6RBuV2PdRk",
      "spotify:track:4xigPf2sigSPmuFH3qCelB",
      "spotify:track:66hayvUbTotekKU3H4ta1f",
      "spotify:track:22pjmqZq2oTZtEThEt66Zn",
      "spotify:track:13HgktGt4RdYj0QmF1ELZO",
      "spotify:track:5N4erncE7kuUccm7zEmwzk",
      "spotify:track:54hA0ldJYyT1huGfSeOjdQ",
      "spotify:track:4lJNen4SMTIJMahALc3DcB",
      "spotify:track:7dH9TPjTWQ60wOJkmYay8a",
      "spotify:track:3oByO94xgLnworeBgkCsGo",
    ],
  },
  {
    ticket_band: "Salt-N-Pepa",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "100700" },
    band_id: "7wqtxqI3eo7Gn1P7SpP6cQ",
    sp_band_name: "Salt-N-Pepa",
    link: "https://open.spotify.com/artist/7wqtxqI3eo7Gn1P7SpP6cQ",
    uri: "spotify:artist:7wqtxqI3eo7Gn1P7SpP6cQ",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e0231ac4ea81876d18519e4b6eb",
    topTrackURIs: [
      "spotify:track:0Pu71wxadDlB8fJXfjIjeJ",
      "spotify:track:6sT9MWlJManry3EQwf4V80",
      "spotify:track:7sJN693sYKEIEMu7fc5VnJ",
      "spotify:track:6hTBP6QLwJdxbKyLlLXrGo",
      "spotify:track:6CUWzTRmC1GjjSDTtiVfsI",
      "spotify:track:5UKGE3tI0s5Lq0Puf6Fn0S",
      "spotify:track:01XoxF27D3Hdz4AnvczcvY",
      "spotify:track:64VKnOE7xkcDBlShRUpJgd",
      "spotify:track:4KNuN3Sen5BzF5nv8V00F1",
      "spotify:track:1ZYYVni68dmk8uwMhrLdC6",
    ],
  },
  {
    ticket_band: "Mavis Staples",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "101000" },
    band_id: "0cTSCsVx04SSht9V6cpKN0",
    sp_band_name: "Mavis Staples",
    link: "https://open.spotify.com/artist/0cTSCsVx04SSht9V6cpKN0",
    uri: "spotify:artist:0cTSCsVx04SSht9V6cpKN0",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e0227d12475983658195016bdf3",
    topTrackURIs: [
      "spotify:track:5PqC3OJ24NIO5pP7me68dn",
      "spotify:track:03qSYwxRCavJccioep27Sx",
      "spotify:track:3v7yjJ7XSDK0CVQSxmH0d1",
      "spotify:track:7BdOM9rzbOeyo7T1qZPMgQ",
      "spotify:track:2REeTHmiO6kbkNTwkolGwC",
      "spotify:track:3gP5iYm2qQlz8LDJUm4suS",
      "spotify:track:5qCvajGQcgKD5mSAKXuTKJ",
      "spotify:track:6w23sxZepVSmRiTLDsP5ou",
      "spotify:track:3Mc3GTTm9MaTRDkBolbDHQ",
      "spotify:track:7uPnE8YMOB35uV4PSYwXLs",
    ],
  },
  {
    ticket_band: "Chet Faker",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "101100" },
    band_id: "6UcJxoeHWWWyT5HZP064om",
    sp_band_name: "Chet Faker",
    link: "https://open.spotify.com/artist/6UcJxoeHWWWyT5HZP064om",
    uri: "spotify:artist:6UcJxoeHWWWyT5HZP064om",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02e22ce077d8cb2d990aced237",
    topTrackURIs: [
      "spotify:track:06WnUZymWyJamDivTWqJZA",
      "spotify:track:2xD7RvKFJl52xyds3wQFXQ",
      "spotify:track:7jJsme36M90Cn6aYYC2l3t",
      "spotify:track:03qDVofuUUQSsSQCLWX0eF",
      "spotify:track:3vDa2fcL7Ge1jQVKJ3uIOA",
      "spotify:track:2Xn7cHKdRP0hBXaUr38J7R",
      "spotify:track:40H5MGB07FCEmrgHBlmLDU",
      "spotify:track:5lGoX0XHR2ystyz0OF3Kv5",
      "spotify:track:6CohXotXOrMVAB0bSPzqzm",
      "spotify:track:70CbWY20oyqDQHM7xUOhfQ",
    ],
  },
  {
    ticket_band: "Matt Maeson",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "101900" },
    band_id: "7gHscNMDI8FF8pcgrV8eIn",
    sp_band_name: "Matt Maeson",
    link: "https://open.spotify.com/artist/7gHscNMDI8FF8pcgrV8eIn",
    uri: "spotify:artist:7gHscNMDI8FF8pcgrV8eIn",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02361d711120142f467651a312",
    topTrackURIs: [
      "spotify:track:6bLU8e0LGyztE9iD5DWBQ1",
      "spotify:track:12rhvKDK2FfHTZZ1sSAHDG",
      "spotify:track:7tySfDFfBiCjraLdoy6In5",
      "spotify:track:3ULF7KLO1zorr3sAVKR2EG",
      "spotify:track:4A8pBxx0of2Y8r56dT0atf",
      "spotify:track:2AfgUQ2BSxGynkc5eoHIrE",
      "spotify:track:5BcgMsAhoEgR6nmZHhAZEg",
      "spotify:track:2Y2nvGDYoKXihBx5KBIugX",
      "spotify:track:1FCwkiooaMCY8YpQdSJ0Gc",
      "spotify:track:3DAQWIPCCpmPDrb02wFrxb",
    ],
  },
  {
    ticket_band: "lovelytheband",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "102000" },
    band_id: "4KJ6jujcNPzOyhdNoiNftp",
    sp_band_name: "lovelytheband",
    link: "https://open.spotify.com/artist/4KJ6jujcNPzOyhdNoiNftp",
    uri: "spotify:artist:4KJ6jujcNPzOyhdNoiNftp",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e0285ea5f82c855acb4476b046c",
    topTrackURIs: [
      "spotify:track:6XcfKZvJio9Z0fQy11GnNX",
      "spotify:track:2iZDkmDeRoqatmOLGUjgjA",
      "spotify:track:2tijppLc0gaWA2AfPDANvq",
      "spotify:track:3Q0ML7kvjcGOr9QnvfDz8a",
      "spotify:track:2crw1sfb4qbWvq3z9cZPRN",
      "spotify:track:4euXJuErBCqH2LEApfxI6i",
      "spotify:track:3ZM7EQicqJZinzks0T4Zrq",
      "spotify:track:4hTApLB99sWDeb1RPsrSye",
      "spotify:track:09akcdeCiV2jIl6x9WpmxA",
      "spotify:track:6WqeLLexWFXNqwVVpu8dUy",
    ],
  },
  {
    ticket_band: "Mallrat",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "102100" },
    band_id: "4OSArit7O2Jaj4mgf3YN7A",
    sp_band_name: "Mallrat",
    link: "https://open.spotify.com/artist/4OSArit7O2Jaj4mgf3YN7A",
    uri: "spotify:artist:4OSArit7O2Jaj4mgf3YN7A",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e029427e46a9acb1a48903e6b07",
    topTrackURIs: [
      "spotify:track:3vLByi1CdmNJPpTtOdKqAQ",
      "spotify:track:10yYDp1Lnac8zEIYiCk1sp",
      "spotify:track:3II5NhDhjzIessLfaSjPQn",
      "spotify:track:6MynbspeogZ1SeMXsoD0Nf",
      "spotify:track:2SonpVAvJS3aOi63oEOTlQ",
      "spotify:track:0ZqhPp0HEoMGVUOy0Powld",
      "spotify:track:00hnbpoSjLscenpW2LzPqs",
      "spotify:track:0UV2btQxu47HidfjAaM6f8",
      "spotify:track:6PwwPfIpqnQOVJUCkYUJcH",
      "spotify:track:1OoqGyjrk8s8NDoE2aW6d0",
    ],
  },
  {
    ticket_band: "Preston Pablo",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "102900" },
    band_id: "5TvdGhdmRObqOkU6eGfXb5",
    sp_band_name: "Preston Pablo",
    link: "https://open.spotify.com/artist/5TvdGhdmRObqOkU6eGfXb5",
    uri: "spotify:artist:5TvdGhdmRObqOkU6eGfXb5",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02f62169327210cf3f933da737",
    topTrackURIs: [
      "spotify:track:079mntueS2KWjxVqOHjG70",
      "spotify:track:2ztJaMY9CjoX53xO1MtQTl",
      "spotify:track:4sqIbiX3BwlYU2rT4Vuc8K",
      "spotify:track:1qG2NSd9c8wddWFmPty7ib",
      "spotify:track:6vLwsGft7DnZixQVgFlKgU",
      "spotify:track:532mumj8LQy0XYRT9aTeOD",
      "spotify:track:5Qc4rsxOalgHGLjnG00gCT",
      "spotify:track:15sxJRnKRkra0qn2rFwiqu",
      "spotify:track:3oafbB3oIvGF8IxgDOfYJV",
      "spotify:track:1QEVs41uQSdW3KcB2RtDDW",
    ],
  },
  {
    ticket_band: "Lindsay Bryan",
    ticket_date: "Sept 16 @ The Park",
    weekend: "The Park",
    date: "Sept 16",
    day: "Sept 16",
    orderNum: { $numberInt: "106300" },
    band_id: "6xB8HBOnEskxinqCnZoFJP",
    sp_band_name: "Lindsay Bryan",
    link: "https://open.spotify.com/artist/6xB8HBOnEskxinqCnZoFJP",
    uri: "spotify:artist:6xB8HBOnEskxinqCnZoFJP",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02f5c25c2cdcbc4f70eb3ee781",
    topTrackURIs: [
      "spotify:track:24N6uH5Vh3mAU5GvVuBIBQ",
      "spotify:track:0EQGhobS4ekMS5DjuEAhot",
      "spotify:track:7z9UQctqMs5smjLfugIT6F",
      "spotify:track:3pdOo2XAKCv9JAOZjl1sGV",
      "spotify:track:6eGPqiOPJmPtiVrV2z9Teh",
      "spotify:track:5SM5lA9DDzsvpKYO3D5nKv",
    ],
  },
  {
    ticket_band: "Stephen Marley",
    ticket_date: "Sept 17 @ The Park",
    weekend: "The Park",
    date: "Sept 17",
    day: "Sept 17",
    orderNum: { $numberInt: "100800" },
    band_id: "0CIwCGmQMqHqiblnZlFia1",
    sp_band_name: "Stephen Marley",
    link: "https://open.spotify.com/artist/0CIwCGmQMqHqiblnZlFia1",
    uri: "spotify:artist:0CIwCGmQMqHqiblnZlFia1",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e024d8b1dc04e30f99815260ef7",
    topTrackURIs: [
      "spotify:track:1Bsl6Jw7bJtQ4pc7OQREog",
      "spotify:track:5wgy309XNqFkqj8MMDquvj",
      "spotify:track:6Ja9BBstKHYveAjRBgM8Oy",
      "spotify:track:7b2WilS8iNSF8PcU17IMdC",
      "spotify:track:5T45lmz64b4W184v23tYvd",
      "spotify:track:3XLnWcWtanFiVtncaF1vwh",
      "spotify:track:3eRlXM0tGtAuBuUGuJRxxw",
      "spotify:track:6NlR4U1EMSXvHeFZO6s1VB",
      "spotify:track:7xDDW2C31HVuz0riQkMrF5",
      "spotify:track:7sWHIFWauKqIXFPvVA4UTa",
    ],
  },
  {
    ticket_band: "Chris Lake",
    ticket_date: "Sept 7",
    weekend: "Electric Avenue",
    date: "Sept 7",
    day: "Sept 7",
    orderNum: { $numberInt: "100300" },
    band_id: "5Igpc9iLZ3YGtKeYfSrrOE",
    sp_band_name: "Chris Lake",
    link: "https://open.spotify.com/artist/5Igpc9iLZ3YGtKeYfSrrOE",
    uri: "spotify:artist:5Igpc9iLZ3YGtKeYfSrrOE",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e0233e18b9b63b4de1887880cb5",
    topTrackURIs: [
      "spotify:track:74nEGIzIefJhJ5qX7NeIAz",
      "spotify:track:2e2yKavdT6WQzzMHwNtPFa",
      "spotify:track:7dsImih2L25fa6qjNphBI7",
      "spotify:track:2SSFvQBwsxeazzo7z5l9gD",
      "spotify:track:5JeBHduTGxXxytZFXBcIlB",
      "spotify:track:5PZI5xTcMq8FsCcEroth7S",
      "spotify:track:4skbQNtyjy8A7mo8oqe2oD",
      "spotify:track:6RIbDs0p4XusU2PZSiDgeZ",
      "spotify:track:0SmyaVrzL7j3R9k3pkJgUh",
      "spotify:track:39aowVnxyzMDZOmrgsN4MU",
    ],
  },
  {
    ticket_band: "Paris Hilton",
    ticket_date: "Sept 8",
    weekend: "Electric Avenue",
    date: "Sept 8",
    day: "Sept 8",
    orderNum: { $numberInt: "100600" },
    band_id: "1vkJFCwstOoJO7yQ4lTtLK",
    sp_band_name: "Paris Hilton",
    link: "https://open.spotify.com/artist/1vkJFCwstOoJO7yQ4lTtLK",
    uri: "spotify:artist:1vkJFCwstOoJO7yQ4lTtLK",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02442533891bd8dc4c1ce79049",
    topTrackURIs: [
      "spotify:track:71V89tJj9CboDyzncO6ZN2",
      "spotify:track:5GUZiPY2HnJMk6ZMpevpMS",
      "spotify:track:6mugfZWz63m4VwRgW9Pbrd",
      "spotify:track:4XRGwyAARL21fesc6BvliF",
      "spotify:track:7dMOGWgmchQKPmCD4vDttH",
      "spotify:track:6jRinD1LZTMwaf7B8BnRS6",
      "spotify:track:4SCFPqnnocBHUBnxys9AFa",
      "spotify:track:5WrYj9jc55HrWJG1JQowDa",
      "spotify:track:1hZ7LSB05aNMX2Nw73DFiR",
      "spotify:track:4iPkafvcL6CeyAcsvZERCk",
    ],
  },
  {
    ticket_band: "Run The Jewels",
    ticket_date: "Sept 9",
    weekend: "Electric Avenue",
    date: "Sept 9",
    day: "Sept 9",
    orderNum: { $numberInt: "100400" },
    band_id: "4RnBFZRiMLRyZy0AzzTg2C",
    sp_band_name: "Run The Jewels",
    link: "https://open.spotify.com/artist/4RnBFZRiMLRyZy0AzzTg2C",
    uri: "spotify:artist:4RnBFZRiMLRyZy0AzzTg2C",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e02708b420d0de80525f3d63206",
    topTrackURIs: [
      "spotify:track:7satW8tFLasyZbftvrWFBP",
      "spotify:track:5taqLrLouA4vCjM7ZQpEtW",
      "spotify:track:3RlurnnuVkVbaN6lul4136",
      "spotify:track:1AESnzWt4iMrEPGG7TjXAa",
      "spotify:track:0C0OKMDnOvUyccUmwZO8AW",
      "spotify:track:101KS2AYeWa98ltX4ewE7h",
      "spotify:track:1EjzcBTVLV7ATtdsQwyV31",
      "spotify:track:10vS4ZLi4XWlIsNXSQXgqh",
      "spotify:track:0y1mw940RjaXJ55VXFoAbM",
      "spotify:track:4OKmlgkeGXxdnT7jVGmKbX",
    ],
  },
  {
    ticket_band: "Miina",
    ticket_date: "Sept 17 @ The Park",
    weekend: "The Park",
    date: "Sept 17",
    day: "Sept 17",
    orderNum: { $numberInt: "103899" },
    band_id: "2be45mouasgEeyH4Tgm4fB",
    sp_band_name: "Miina",
    link: "https://open.spotify.com/artist/2be45mouasgEeyH4Tgm4fB",
    uri: "spotify:artist:2be45mouasgEeyH4Tgm4fB",
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e022d8f905c060b0dfad6065198",
    topTrackURIs: [
      "spotify:track:1idPrmJk9PlmFsupge2Xrf",
      "spotify:track:2R3lSZ2AHGA7EPFgmsdFdy",
      "spotify:track:0SvDIepkDTQvseFXwcnjPi",
      "spotify:track:3jlM9gSxFFBIv2TgAbxxzU",
      "spotify:track:1gMJlkYo6IZF3QGJ6n78HO",
    ],
  },
]);

db.createCollection("whistlemania");
db.whistlemania.insertMany([
  {
    ticket_band: "Peach Pyramid",
    ticket_date: "June 24 @ 3:30 PM - 4:30 PM",
    ticket_price: "Free",
    date: "June 24 2023",
    band_id: "08IwPDrMEOqfuaHXHhjuKy",
    sp_band_name: "Peach Pyramid",
    link: "https://open.spotify.com/artist/08IwPDrMEOqfuaHXHhjuKy",
    uri: "spotify:artist:08IwPDrMEOqfuaHXHhjuKy",
    topTrackURIs: [
      "spotify:track:4eAkWDlUPN1jwWj7tpKFhh",
      "spotify:track:3hg7w6mAN7EdrJCycyHlNO",
      "spotify:track:5P4GY6UzEkcM197aOTP2nW",
      "spotify:track:4mP3VdCTgoaA9tSTlQfHAA",
      "spotify:track:25Qf2kvCtpDiaoxpBrvNFz",
    ],
    albumArtUrl: "https://i.scdn.co/image/ab67616d00001e0257783eac1a29100098f11087",
  },
]);
